
-- --------------------------------------------------------

--
-- Estrutura da tabela `tb_atividade_economica`
--

CREATE TABLE `tb_atividade_economica` (
  `codigo` int(11) NOT NULL,
  `setor` int(11) DEFAULT NULL,
  `subsetor` int(11) DEFAULT NULL,
  `atividade` varchar(50) DEFAULT NULL,
  `descricao` varchar(259) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Extraindo dados da tabela `tb_atividade_economica`
--

INSERT INTO `tb_atividade_economica` (`codigo`, `setor`, `subsetor`, `atividade`, `descricao`) VALUES
(3, 523, 517, 'Cultura de Grãos', 'Grãos: trigo, arroz, milho, soja e outros grãos'),
(4, 523, 517, 'Outras Culturas', 'Culturas: algodão, fumo, cana de açúcar, batata, etc., exceto grãos'),
(5, 523, 517, 'Legumes e melões', 'Legumes e melões'),
(6, 523, 517, 'Frutas e Nozes', 'Frutas (uvas, cítricas, efêmeras, etc.) e nozes de árvores'),
(7, 523, 517, 'Especialidades hortifrutíferas', 'Especialidades hortifrutíferas: plantas e frutas criadas em viveiro'),
(8, 523, 517, 'Outras Culturas', 'Outras culturas, principalmente agrícolas'),
(10, 523, 518, 'Pecuária', 'Pecuária (gado bovino, pastos, suínos, ovelhas, cabras e outros animais, exceto leite e aves)'),
(11, 523, 518, 'Leite', 'Leite'),
(12, 523, 518, 'Aves e Ovos', 'Aves e ovos de galinha, peru, etc., incubadoras'),
(13, 523, 518, 'Especialidades Animais', 'Especialidades animais: coelhos, cavalos e outros eqüinos, animais de pele e hidrocultura'),
(14, 523, 518, 'Pecuária e lavoura: produção mista', 'Pecuária e lavoura: produção mista'),
(15, 523, 518, 'Outros Animais', 'Outras criações de animais'),
(17, 523, 519, 'Preparação de Solo', 'Serviços de preparação do solo'),
(18, 523, 519, 'Serviços em Culturas', 'Serviços de culturas agrícolas: plantio, proteção, colheita, preparação para comercialização'),
(19, 523, 519, 'Serviços Veterinários', 'Serviços veterinários para pecuária e demais tipos de animais'),
(20, 523, 519, 'Outros Serviços em Animais', 'Serviços de animais, exceto veterinários'),
(21, 523, 519, 'Mão de Obra e Administração', 'Serviços de mão-de-obra e administração de propriedades rurais'),
(22, 523, 519, 'Paisagismo e Jardinaria', 'Serviços de paisagismo e jardinagem, com árvores e plantas ornamentais'),
(24, 523, 520, 'Floresta Madereira', 'Terrenos com árvores para produção de madeira'),
(25, 523, 520, 'Produtos Florestais', 'Produtos florestais'),
(26, 523, 520, 'Serviços de Florestamento', 'Serviços de florestamento'),
(28, 523, 521, 'Pesca Comercial', 'Pesca comercial de peixes, mariscos e outros produtos marinhos'),
(29, 523, 521, 'Piscicultura', 'Viveiros para criação e preservação de peixes'),
(30, 523, 521, 'Caça e Captura', 'Caça, captura e procriação de animais de caça'),
(32, 523, 522, 'Ferro', 'Minérios de ferro'),
(33, 523, 522, 'Cobre', 'Minérios de cobre'),
(34, 523, 522, 'Chumbo e Zinco', 'Minérios de chumbo e zinco'),
(35, 523, 522, 'Ouro e Prata', 'Minérios de ouro e prata'),
(36, 523, 522, 'Outros Ferrosos', 'Outros minérios ferrosos, exceto vanádio (p.ex. tungstênio)'),
(37, 523, 522, 'Serviços de Lavra', 'Serviços de lavra de metais'),
(38, 523, 522, 'Outros Metales', 'Minérios de metais diversos: urânio, rádio, vanádio'),
(40, 523, 523, 'Carvão Betuminoso', 'Lavra de carvão betuminoso e linhita, a céu aberto ou subterrânea'),
(41, 523, 523, 'Antracito', 'Lavra de antracito'),
(42, 523, 523, 'Serviços de Lavra de Carvão', 'Serviços de lavra de carvão'),
(44, 523, 524, 'Óleo Bruto e Gás Natural', 'Óleo bruto e gás natural'),
(45, 523, 524, 'Líquidos de Gás Natural', 'Líquidos de gás natural'),
(46, 523, 524, 'Serviços em Campos Petróleo/Gás', 'Serviços de campo de petróleo e gás: exploração, perfuração, etc.'),
(48, 523, 525, 'Pedra em Bloco', 'Extração de pedra em bloco'),
(49, 523, 525, 'Pedra Moída', 'Pedra moída e britada (calcário, granito, etc.), inclusive enrocamento'),
(50, 523, 525, 'Areia e Cascalho', 'Areia de construção, areia de uso industrial, e cascalho'),
(51, 523, 525, 'Argila e Cerâmica', 'Argila, caulim, cerâmica e outros minerais refratários'),
(52, 523, 525, 'Químicos e Fertilizantes', 'Mineração de produtos químicos e fertilizantes, p.ex. potássio e fosfatos'),
(53, 523, 525, 'Serviços Minerais', 'Serviços de minerais não metálicos'),
(54, 523, 525, 'Outros Minerais', 'Outros minerais não metálicos, exceto Combustíveis'),
(56, 519, 526, 'Construção de Residências', 'Empreiteiras de construção em geral - edifícios residenciais, casas e prédios'),
(57, 519, 526, 'Construção e Incorporação', 'Construção e incorporação de casas residenciais'),
(58, 519, 526, 'Construção não Residencial', 'Empreiteiras de construção em geral, edificações industriais, comerciais, depósitos, etc.'),
(60, 519, 527, 'Ruas e Rodovias', 'Construção de rodovias e ruas'),
(61, 519, 527, 'Construção Pesada', 'Construção pesada (pontes, túneis, viadutos, canais, esgotos), exceto rodovias e ruas'),
(63, 519, 528, 'Encanamento e Refrigeração', 'Encanamento, aquecimento e ar condicionado'),
(64, 519, 528, 'Pintura e Papel de Parede', 'Pintura e colocação de papel de parede'),
(65, 519, 528, 'Instalações Elétricas', 'Instalações elétricas'),
(66, 519, 528, 'Revestimentos', 'Colocação de pedras, ladrilhos, reboco, vedação, acústica, revestimento, azulejos, mármore, granito'),
(67, 519, 528, 'Marcenaria e Pisos', 'Serviços de marcenaria e colocação de pisos e similares'),
(68, 519, 528, 'Telhado e Cobertura', 'Serviços de colocação de telhados e coberturas metálicas'),
(69, 519, 528, 'Concretação', 'Serviços em concreto'),
(70, 519, 528, 'Poços Artesianos', 'Perfuração de poços artesianos'),
(71, 519, 528, 'Outras Empreiteras', 'Empreiteiras especializadas diversas: estruturas metálicas, serviços em vidro, escavações, fundações, demolições, etc.'),
(73, 519, 529, 'Derivados de Carne', 'Produtos derivados de carne: salsichas, lingüiças, salames, embutidos, frigoríficos, abate e processamento de aves'),
(74, 519, 529, 'Laticínios', 'Laticínios: leite, manteiga, queijo natural e processado, lácteos secos, condensados ou evaporados, sorvetes e outras sobremesas congeladas'),
(75, 519, 529, 'Conservas e Enlatados', 'Produtos em lata e conservas de frutas e legumes; geléias e compotas; frutas, vegetais e sopas desidratadas; molhos e temperos; frutas, sucos, legumes e demais alimentos congelados'),
(76, 519, 529, 'Moagem de Grãos', 'Farinhas, cereais, arroz descascado; moinhos e óleo de milho; massas de farinha e preparados; rações para cães, gatos, aves e demais animais'),
(77, 519, 529, 'Pães e Afins', 'Produtos de padaria: pães, bolos, bolachas e biscoitos, inclusive congelados'),
(78, 519, 529, 'Açúcar e Doces', 'Açúcar (processamento e refino, de cana e beterraba) e produtos de confeitaria, doces, chocolates, chicletes, nozes e castanhas torradas'),
(79, 519, 529, 'Óleos e Gorduras', 'Gorduras comestíveis, vegetais e animais (inclusive margarina), e óleos de algodão, soja e outros (exceto milho)'),
(80, 519, 529, 'Bebidas', 'Bebidas: cerveja, malte, vinho, conhaque, aguardente, outros destilados; xaropes, refrigerantes e agua mineral'),
(81, 519, 529, 'Outros Alimentos Preparados', 'Outros alimentos: pescados e frutos do mar, frescos, em lata ou defumados; café torrado; batata frita e salgadinhos; gelo; massas e outros'),
(83, 519, 530, 'Cigarros', 'Cigarros'),
(84, 519, 530, 'Charutos', 'Charutos'),
(85, 519, 530, 'Fumo de Mascar', 'Fumo para mascar e fumar'),
(86, 519, 530, 'Processamento de Fumo', 'Ressecagem e processamento de folhas de fumo'),
(88, 519, 531, 'Tecelagem de Algodão', 'Tecelagem de algodão em peças largas'),
(89, 519, 531, 'Tecelagem de Sintéticos', 'Tecelagem de tecidos sintéticos de trama aberta em peças largas'),
(90, 519, 531, 'Tecelagem de Lã', 'Tecelagem de lã em peças largas'),
(91, 519, 531, 'Tecidos Estreitos', 'Tecelagem de algodão, lã,  seda de fibras sintéticas em peças estreitas'),
(92, 519, 531, 'Malharias', 'Malharias: acabamento de malha circular e urdida; meias, meia calça, artigos de malha, artigos íntimos em malha'),
(93, 519, 531, 'Acabamento Têxtil', 'Tingimento e acabamento de têxteis de algodão e sintéticos'),
(94, 519, 531, 'Carpetes e Tapetes', 'Carpetes e tapetes'),
(95, 519, 531, 'Fiações', 'Fiações de fios e linhas de algodão, seda, lã, fibras naturais e sintéticas; texturização e enlaçamento'),
(96, 519, 531, 'Outros Têxteis', 'Demais têxteis: tecidos revestidos (exceto emborrachados), lonas e tecidos para pneus, cordas, trançados e outros tecidos produzidos sem tecelagem'),
(98, 519, 532, 'Ternos e Casacos Masculinos', 'Ternos, casacos e sobretudo para homens, rapazes e meninos'),
(99, 519, 532, 'Demais Roupas Masculinas', 'Acessórios para homens e rapazes, roupas profissionais e similares: camisas; roupa íntima e de dormir; gravatas, lenços e cachecós; calças'),
(100, 519, 532, 'Roupas Externas Femeninas', 'Roupas para moças e senhoras: blusas, camisas, vestidos, tailleurs, casacos, saias, calças'),
(101, 519, 532, 'Roupas Íntimas Femeninas', 'Roupas íntimas para senhoras e crianças: pijamas, calcinhas, soutiens, cintas'),
(102, 519, 532, 'Chapéus, Gorros e Bonês', 'Chapéus, gorros e bonés'),
(103, 519, 532, 'Roupas Infantis', 'Roupas infantis: vestidos, blusas, camisas e demais roupas para crianças e bebês'),
(104, 519, 532, 'Roupas de Pele', 'Confecções em peles'),
(105, 519, 532, 'Outras Roupas', 'Luvas sociais e de trabalho (exceto em couro); batas e robes; capas de chuva e impermeáveis; confecções com forro em pele; cintos e outros acessórios'),
(106, 519, 532, 'Outros Textiles', 'Demais produtos de fabricação têxtil: cortinas, sacos e sacolas, artigos de lona'),
(108, 519, 533, 'Exploração florestal', 'Exploração florestal'),
(109, 519, 533, 'Serrarias', 'Serrarias e usinas de aplainamento em geral, inclusive serrarias de madeiras para assoalhos e madeiras especiais'),
(110, 519, 533, 'Marcenaria', 'Marcenaria, cozinhas, chapas e compensados de madeira tenra e resistente, estruturas de madeira'),
(111, 519, 533, 'Embalagens de Madeira', 'Embalagens de madeira: caixas de madeira pregada e/ou colada, pallets e demais embalagens de madeira'),
(112, 519, 533, 'Construções de Madeira', 'Construções de madeira (casas pré-fabricadas) e casas móveis (trailers residenciais em madeira)'),
(113, 519, 533, 'Outros Produtos de Madeira', 'Demais produtos de madeira, inclusive serviços de tratamento de madeira e produtos de madeira reconstituída'),
(115, 519, 534, 'Móveis Residenciais', 'Móveis residenciais de madeira, estofados, de metal; sofás, camas, colchões; móveis e gabinetes para TV, aúdio, vídeo, computador, máquina de costura; etc.'),
(116, 519, 534, 'Móveis de Escritório', 'Móveis para instalações comerciais (escritórios, lojas, repartições, etc) de madeira, de metal, etc.'),
(117, 519, 534, 'Divisória e Estantes', 'Divisórias e estantes (de madeira, metal ou outros) para escritórios e lojas'),
(118, 519, 534, 'Outros Móveis', 'Demais móveis e acessórios: venezianas, persianas e toldos (exceto de tecido); outros tipos de móveis'),
(120, 519, 535, 'Polpa de Papel', 'Fábrica de polpa de papel'),
(121, 519, 535, 'Papel', 'Fábrica de papel'),
(122, 519, 535, 'Papelão', 'Fábrica de papelão'),
(123, 519, 535, 'Caixas e Embalagens de Papelão', 'Caixas de papelão montáveis e dobráveis; caixas de fibra, sólida e corrugada; latas, tubos e tambores de fibra; embalagens para alimentos'),
(124, 519, 535, 'Outros Derivados de Papel', 'Produtos fabricados de papel e papelão (exceto embalagens e caixas): papéis para embalagem, laminados, revestidos; papel secante; papel higiênico; envelopes; artigos de papelaria; formulários contínuos; etc.'),
(126, 519, 536, 'Jornais', 'Jornais'),
(127, 519, 536, 'Revistas', 'Revistas Periódicas'),
(128, 519, 536, 'Livros', 'Publicação, impressão e encadernação de livros'),
(129, 519, 536, 'Outras Publicações', 'Demais tipos de publicações'),
(130, 519, 536, 'Impressão Comercial', 'Impressão comercial: xerografia, litografia, gravura e outras'),
(131, 519, 536, 'Formulários Comerciais', 'Formulários comerciais: livros de registro, notas fiscais e similares'),
(132, 519, 536, 'Cartões de Felicitações', 'Cartões de felicitações'),
(133, 519, 536, 'Livros em Branco e Encadernação', 'Livros em branco, cadernos, blocos, arquivos, pastas para folhas soltas, encadernações e similares'),
(134, 519, 536, 'Serviços para Gráficas', 'Indústrias e Serviços específicos para o setor de impressão: composição, fotolitos, chapas, etc.'),
(136, 519, 537, 'Inorgânicos Industriais', 'Produtos químicos inorgânicos industriais: álcalis e cloros; gases industriais; pigmentos e demais produtos químicos inorgánicos industriais'),
(137, 519, 537, 'Plásticos e Sintéticos', 'Materiais e resinas plásticas, borracha sintética, fibras celulósicas e orgánicas sintéticas e similares, exceto vidros'),
(138, 519, 537, 'Medicamentos', 'Produtos medicinais químicos e botânicos, farmaceúticos, substâncias para exames e diagnósticos e produtos biológicos'),
(139, 519, 537, 'Limpeza e Cosméticos', 'Produtos de limpeza (sabão, detergente, polidores, água sanitária, desinfetante, etc.) e cosméticos (perfumes e produtos de toalete)'),
(140, 519, 537, 'Tintas e Vernizes', 'Tintas, vernizes, lacas, esmaltes e produtos correlatos'),
(141, 519, 537, 'Orgânicos e Industriais', 'Produtos químicos industriais orgânicos: resinas extraídas da madeira; tintas, pigmentos e aromáticos orgánicos; etc.'),
(142, 519, 537, 'Fertilizantes', 'Fertilizantes nitrogenados, fosfatados, misturas; pesticidas e demais produtos químicos agrícolas'),
(143, 519, 537, 'Outros Produtos Químicos', 'Adesivos, vedadores, explosivos, tintas químicas para impressão, carbono, e demais produtos e preparados químicos'),
(145, 519, 538, 'Refinação de Petróleo', 'Refinação de petróleo'),
(146, 519, 538, 'Materiais Asfálticos', 'Materiais asfálticos para pavimentação (composto, blocos e panos asfálticos) e telhados (feltros e revestimentos asfálticos)'),
(147, 519, 538, 'Outros Produtos de Petróleo', 'Óleos lubrificantes, graxas e demais produtos derivados de petróleo e carvão; produtos petroquímicos'),
(148, 519, 538, 'Usina de Álcool', 'Usina produtora de álcool carburante'),
(150, 519, 539, 'Pneus e Câmaras', 'Pneus e câmaras de ar'),
(151, 519, 539, 'Calçados de Borracha e Plástico', 'Calçados de borracha e plástico'),
(152, 519, 539, 'Mangueiras e Correias', 'Gaxetas, juntas, mangueiras, correias, vedações e similares, todos de borracha'),
(153, 519, 539, 'Outros Produtos Borracha', 'Produtos de borracha para uso mecânico e demais produtos de borracha'),
(154, 519, 539, 'Outros Produtos Plástico', 'Láminas, películas, perfis, tubos e barras de plástico flexível; tubos e conexões; garrafas plásticas; espumas plásticas; resinas plásticas sob encomenda, e demais produtos de plástico'),
(156, 519, 540, 'Curtumes de Couro', 'Curtimento e acabamento de couro'),
(157, 519, 540, 'Solas de Sapato', 'Solas de calçado e demais artigos para fabricação de calçados'),
(158, 519, 540, 'Calçados Diversos', 'Calçados masculinos e femeninos, excetuando os esportivos e os de borracha'),
(159, 519, 540, 'Luvas de Couro', 'Luvas de couro'),
(160, 519, 540, 'Bagagem', 'Malas, bolsas e artigos para viagem'),
(161, 519, 540, 'Bolsas', 'Bolsas e carteiras, masculinas e femeninas, e demais produtos pessoais de couro'),
(162, 519, 540, 'Outros Produtos de Couro', 'Demais produtos de couro'),
(164, 519, 541, 'Vidro Plano', 'Vidro plano'),
(165, 519, 541, 'Vidro Soprado e Prensado', 'Artefatos de vidro soprado (p.ex. recipientes) ou prensado'),
(166, 519, 541, 'Vidro Reciclado', 'Produtos de vidro reciclado'),
(167, 519, 541, 'Cimento Hidraúlico', 'Cimento hidráulico'),
(168, 519, 541, 'Produtos de Argila', 'Produtos de argila: telhas, tijolos, azulejos, pisos de cerâmica, refratários, etc.'),
(169, 519, 541, 'Louças', 'Artigos de louça: vasos sanitários e afins, artigos de cerâmica, louça e porcelanas finas para mesa e cozinha, artigos elétricos de porcelana, etc.'),
(170, 519, 541, 'Concreto e Gesso', 'Blocos, tijolos e outros produtos de concreto, concreto pré-misturado, cal e produtos de gesso'),
(171, 519, 541, 'Pedra, Granito e Mármore', 'Artigos de pedra, granito e mármore'),
(172, 519, 541, 'Outros Produtos Miner. Não Metál', 'Produtos abrasivos, de amianto, minérios e argilas tratadas e moídas, lã mineral, refratários não cerámicos e demais produtos elaborados a partir de minerais não metálicos'),
(174, 519, 542, 'Siderurgia e Produtos Bás.de Aço', 'Siderúrgicas, altos-fornos, produtos eletrometalúrgicos, trefilação de arames e pregos, folhas e barras laminadas, canos e tubos de aço'),
(175, 519, 542, 'Fundições Ferrosas', 'Fundições de ferro (cinzento e maleável) e de aço (moldado ou não)'),
(176, 519, 542, 'Fundições Primárias Não Ferrosas', 'Fundição primária e refino de metais não ferrosos: cobre, alumínio, etc.'),
(177, 519, 542, 'Fundições Secundár. Não Ferrosas', 'Fundição e refinação secundária de metais não ferrosos'),
(178, 519, 542, 'Laminação e Extrusão Não Ferroso', 'Laminação (chapas e folhas), trefilação (arames, fios, isolantes), estiramento e extrusão de metais não ferrosos'),
(179, 519, 542, 'Fundição em Moldes Não Ferrosos', 'Produtos gerados a partir de metais não ferrosos por fundição em moldes'),
(180, 519, 542, 'Outros Produtos Primár. Metal', 'Demais produtos primários de metal, incluindo tratamento térmico de metais'),
(182, 519, 543, 'Latas e Recipientes', 'Latas de metal, barris, tambores e baldes de metal'),
(183, 519, 543, 'Cutelaria e Ferramentas Manuais', 'Cutelaria, ferramentas manuais e de corte, lâminas e serras, ferramentas manuais em geral'),
(184, 519, 543, 'Encanamento e Aquecimento ñ Elét', 'Artigos de ferro esmaltado e metal sanitário, peças e acessórios de metal para encanamentos, equipamentos para aquecimento (exceto elétrico e de ar quente) e artefatos sanitários de metal'),
(185, 519, 543, 'Estruturas Metálicas', 'Produtos estruturados em metal: portas, caixilhos, esquadrias e moldes, produtos fabricados de chapas e folhas, produtos ornamentais de metal, etc.'),
(186, 519, 543, 'Parafusos, Porcas, Arruelas', 'Produtos de máquinas de parafusos, porcas, parafusos, rebites e arruelas'),
(187, 519, 543, 'Metal Forjado e Estampado', 'Produtos de metal (ferro, aço e não ferrosos) forjado e estampado, incluindo estamparia para automóveis e tampas de metal'),
(188, 519, 543, 'Outros Serviços em Metal', 'Revestimento (p.ex. galvanização, cromação, anodização, polimento e coloração), gravação e serviços assemelhados'),
(189, 519, 543, 'Material Bélico Leve', 'Material bélico (munição, armas leves, etc) e acessórios, exceto veículos e mísseis'),
(190, 519, 543, 'Outros Produtos de Metal', 'Demais produtos de metal, incluindo: válvulas industriais, válvulas e acessórios para líquidos, molas de aço e arame, outros produtos de arame, canos de metal, encaixes de válvulas e tubos, folhas de metal, etc.'),
(192, 519, 544, 'Motores e Turbinas', 'Motores de combustão interna, turbinas hidráulicas (a vapor e a gás) e unidades geradoras'),
(193, 519, 544, 'Máquinas Agrícolas', 'Maquinás e equipamentos agrícolas, incluindo pequenos tratores e equipamentos para jardinagem'),
(194, 519, 544, 'Máquinas para Construção e Miner', 'Equipamentos e máquinas pesadas para mineração (incluindo petróleo e gás) e construção; elevadores e escadas rolantes; esteiras transportadoras e equipamentos; guinchos, guindastes industriais; caminhões, tratores, trailers e empilhadeiras industriais'),
(195, 519, 544, 'Máquinas para Metalúrgicas', 'Equipamentos e maquinário para metalurgia: ferramentas não manuais para corte, laminação e moldagem de metal; produção de moldes e formas industriais; ferramentas manuais mecânicas; equipamento para solda a gás e elétrica; etc.'),
(196, 519, 544, 'Máquinas para Outras Indústrias', 'Maquinário especial para outros tipos de indústria (incluindo a têxtil, marcenaria, papelaria, gráfica, alimentícia, etc.)'),
(197, 519, 544, 'Máquinas Gerais para Industria', 'Maquinás usadas em todos os tipos de indústria; p.ex. bombas e equipamentos de bombeamento, rolamentos, compressores de ar e gás, ventiladores, exaustores e purificadores de ar, máquinas para embalar, transmissão de força (correias/engrenagens) e fornos'),
(198, 519, 544, 'Máquinas de Refrigeração', 'Maquinário de refrigeração (máquinas de venda automática, máquinas para lavanderia comercial, refrigeração e aquecimento de ar, bombas de gasolina e graxa) e máquinas para uso em serviços'),
(199, 519, 544, 'Outras máquinas', 'Maquinário e equipamentos industriais e comerciais diversos: carburadores, pistões, anéis e válvulas; cilindros, bombas e motores hidráulicos; balanças, exceto de laboratórios; etc'),
(201, 519, 545, 'Distribuição de Eletricidade', 'Equipamentos de distribuição de energia elétrica: transformadores de todo tipo e quadros de distribuição'),
(202, 519, 545, 'Equipamento Elétrico Industrial', 'Equipamentos industriais elétricos: motores e geradores; produtos de carbono e grafite; relês e controles; etc.'),
(203, 519, 545, 'Eletrodomésticos', 'Eletrodomésticos: para cozinha; geladeiras e freezers; lavadoras e secadoras de roupas; ventiladores; aspiradoras de pó; chuveiros e aquecedores elétricos; etc.'),
(204, 519, 545, 'Iluminação e Fiação', 'Equipamentos de iluminação e fiação elétrica: lâmpadas e artigos de iluminação, artigos usados na montagem de fiações, artigos elétricos para uso em veículos, etc.'),
(205, 519, 545, 'Aúdio e Vídeo Doméstico', 'Equipamentos de áudio e vídeo domésticos: equipamentos de radio, televisão e videocassette; discos e fitas gravadas; etc.'),
(206, 519, 545, 'Equipamentos de Comunicação', 'Equipamentos de comunicação através de telefonia, telegrafia, rádio, televisão, etc.'),
(207, 519, 545, 'Produtos Eletrônicos', 'Equipamentos, componentes e acessórios eletrônicos: tubos, circuitos impressos, semicondutores, capacitores, resistores, bobinas, indutores, conectores, etc.'),
(208, 519, 545, 'Suprimentos para Equipam. Elétr.', 'Suprimentos eletrônicos diversos (pilhas, fitas e discos virgens; etc) e outros equipamentos eletroeletrônicos não classificados'),
(210, 519, 546, 'Veículos Automotores e Acessório', 'Automóveis de passeio, carrocerias para automóveis, ônibus e caminhões, reboques e trailers, peças e acessórios para veículos automotores'),
(211, 519, 546, 'Indústria Aeronaútica', 'Aeronaves, motores e peças, equipamentos auxiliares e peças para aviões'),
(212, 519, 546, 'Estaleiros', 'Estaleiros para construção e reparação de todo tipo de embarcações (barcos, navios, etc)'),
(213, 519, 546, 'Equipamento Ferroviário', 'Equipamentos ferroviários'),
(214, 519, 546, 'Motos e Bicicletas', 'Motocicletas, bicicletas e peças'),
(215, 519, 546, 'Indústria Aeroespacial', 'Mísseis guiados, veículos espaciais, unidades de propulsão, suas peças e acessórios'),
(216, 519, 546, 'Outros Transportes', 'Demais equipamentos de transportes, p.ex. trailers para lazer, tanques para caminhões'),
(218, 519, 547, 'Busca e Navegação', 'Equipamentos de busca e navegação'),
(219, 519, 547, 'Instrumentos de Medida/Controle', 'Instrumentos e móveis para laboratórios; controles automáticos para regulagem de aparelhos e ambientes; instrumentos de medição, teste e controle de líquidos, fluídos, eletricidade, instrumentos óticos e lentes, etc.'),
(220, 519, 547, 'Instrumentos Médicos', 'Instrumentos e aparelhos médicos, cirúrgicos, ortopédicos, protéticos, odontológicos e clínicos, incluindo aparelhos e tubos de raio-x e equipamentos eletroterapêúticos'),
(221, 519, 547, 'Artigos Oftálmicos', 'Artigos oftálmicos'),
(222, 519, 547, 'Fotografia', 'Equipamentos e artigos fotográficos'),
(223, 519, 547, 'Relógios', 'Relógios de pulso, parede e peças para relógios'),
(225, 519, 548, 'Jóias e Prataria', 'Jóias de metal precioso, peças de prata, aço inoxidável, peças folheadas e lapidadas; materiais para joalheiros e serviços de lapidação'),
(226, 519, 548, 'Instrumentos Musicais', 'Instrumentos musicais'),
(227, 519, 548, 'Brinquedos e Artigos Esportivos', 'Brinquedos, jogos e veículos para crianças (incluindo bonecas e bichos de pelúcia) e artigos esportivos e atléticos'),
(228, 519, 548, 'Lápis e Canetas', 'Canetas, lapiseiras, lápis e peças; artigos para marcação e sinalização; papel carbono, fitas e cartuchos para máquinas de escrever e impressoras; materiais para pintura artística e outros materiais para artistas'),
(229, 519, 548, 'Bijuterias e Aviamentos', 'Bijouterias (exceto de metal precioso), fechos, botões, zípers, agulhas, alfinetes e aviamentos diversos'),
(230, 519, 548, 'Outras Indústrias', 'Indústrias manufatureiras diversas, incluindo vassouras e escovas, letreiros e anúncios publicitários, caixões de defunto, revestimentos de piso a base de feltro asfáltico, etc.'),
(232, 521, 549, 'Ferrovias Longa Distância', 'Transporte ferroviário de passageiros, não urbano nem suburbano, e serviços de operação de terminais e controles ferroviários'),
(233, 521, 549, 'Ferrovias Locais', 'Transporte ferroviário de passageiros, urbano e suburbano'),
(235, 521, 550, 'Ônibus Urbano', 'Ônibus de transporte urbano'),
(236, 521, 550, 'Táxis', 'Taxis'),
(237, 521, 550, 'Ônibus não Urbano', 'Ônibus de transporte interurbano e rural'),
(238, 521, 550, 'Ônibus Fretado', 'Fretamento de Ônibus local'),
(239, 521, 550, 'Ônibus Escolares', 'Ônibus e outros veículos para transporte escolares'),
(240, 521, 550, 'Terminais e Manutenção Ônibus', 'Terminais rodoviários e manutenção de veículos automotores para transporte de passageiros'),
(242, 521, 551, 'Carga e Courier', 'Transportes rodoviário de carga e documentos (couriers), com e sem armazenamento, serviços rodoviários de entregas e encomendas'),
(243, 521, 551, 'Armazenagem e Estocagem', 'Armazenagem e estocagem de produtos agrícolas, refrigerados, etc.'),
(244, 521, 551, 'Terminais de Carga', 'Terminais rodoviários para uso exclusivo de veículos de transporte de carga'),
(246, 521, 552, 'Correios', 'Empresa Oficial de Correios e Telégrafos'),
(248, 521, 553, 'Transporte Marítimo Internacion.', 'Transporte marítimo internacional de cargas'),
(249, 521, 553, 'Transporte Marítimo Doméstico', 'Transporte marítimo doméstico de carga'),
(250, 521, 553, 'Transporte Marítimo Lacunar', 'Transporte de cargas em lagos e lacunas'),
(251, 521, 553, 'Outros Transportes Marítimos', 'Outras modalidades de transporte de cargas por via marítima'),
(252, 521, 553, 'Transporte Marítimo de Passageir', 'Transporte marítimo de passageiros, inclusive em balsas e em alto mar'),
(253, 521, 553, 'Serviços Marítimos', 'Serviços marítimos e fluviais: manuseio de cargas, reboques marítimos, marinas, etc'),
(255, 521, 554, 'Transporte Aéreo Regular', 'Transporte aéreo com horário programado e serviços de entrega de malotes'),
(256, 521, 554, 'Transporte Aéreo Fretado', 'Transporte aéreo, linhas não regulares'),
(257, 521, 554, 'Aeroportos', 'Serviços de administração de aeroportos e terminais'),
(259, 521, 555, 'Oleodutos', 'Oleodutos (p.ex. de petróleo cru e/ou refinado)'),
(261, 521, 556, 'Agências de Transporte de Passag', 'Agenciamento de transporte de passageiros, incluindo agências de viagem e operadoras de turismo'),
(262, 521, 556, 'Agências de Transporte de Cargas', 'Agenciamento de serviços de transporte de cargas'),
(263, 521, 556, 'Aluguel de Vagões', 'Aluguel de vagões ferroviários'),
(264, 521, 556, 'Concessionárias de rodovias', 'Empresas que administram rodovias'),
(265, 521, 556, 'Outros Serviços de Transporte', 'Demais serviços para transportes: emabalagens, engradados, instalações de inspeção, etc'),
(267, 521, 557, 'Comunicação Telefônica', 'Serviços de comunicação telefônica fixa, celular e radiotelefônica'),
(268, 521, 557, 'Comunicação Mensagens', 'Comunicações telegráficas, via telex e outras comunicações de mensagens (beeps, pagers, etc)'),
(269, 521, 557, 'Emissoras de Rádio e Televisão', 'Emissoras de programas de rádio e televisão'),
(270, 521, 557, 'Televisão Paga', 'Televisão a cabo e outros serviços de televisão pagos'),
(271, 521, 557, 'Outras Comunicações', 'Demais serviços de comunicações'),
(273, 521, 558, 'Companhias de Eletricidade', 'Companhias de eletricidade'),
(274, 521, 558, 'Companhias de Gás', 'Produção, transmissão e distribuição de gás natural e de petróleo liqüefeito'),
(275, 521, 558, 'Companhias Combinadas', 'Serviços de eletricidade e/ou gás, combinados entre si ou com outros serviços de utilidade pública'),
(276, 521, 558, 'Fornecimento de Água', 'Fornecimento de água potável'),
(277, 521, 558, 'Serviços Sanitários/Coleta Lixo', 'Serviços sanitários (esgotos) e recolhimento de lixos, sobras, entulhos e sucatas'),
(278, 521, 558, 'Vapor e Ar Aquecido/Refrigerado', 'Produção e distribuição de vapor, ar aquecido e/ou refrigerado'),
(279, 521, 558, 'Sistemas de Irrigação', 'Sistemas de irrigação'),
(281, 517, 559, 'Automotores e Autopeças', 'Veículos motorizados (incluindo automóveis), peças e acessórios para veículos, pneus e câmaras de ar; novos e usados'),
(282, 517, 559, 'Móveis e Artigos Domésticos', 'Móveis e artigos domésticos'),
(283, 517, 559, 'Madeiras e Construção', 'Madeiras (compensadas, laminadas, artigos para marcenaria) e outros materiais de construção (tijolos, pedrsa, telhados, revestimentos, isolantes, etc)'),
(284, 517, 559, 'Equipamento Profissional/Comerc.', 'Equipamentos e acessórios para uso profissional e comercial: fotografia, escritório, computadores, periféricos, software, equipamento médico, hospitalar, dentário, oftálmico, etc.'),
(285, 517, 559, 'Metais e Minerais', 'Metais e Minerais, exceto petróleo e derivados'),
(286, 517, 559, 'Produtos Elétricos', 'Produtos elétricos: aparelhos, equipamentos, material elétrico para construção, eletrodomésticos, rádio, TV, VCR, peças e equipamentos eletrônicos'),
(287, 517, 559, 'Ferragens e Encanamentos', 'Ferragens, equipamentos e acessórios para encanamento e aquecimento, refrigeração e ar condicionado'),
(288, 517, 559, 'Máquinas e Equipamentos', 'Máquinas, equipamentos e acessórios para construção, mineração, agricultura, jardinagem, indústrias, prestação de serviços e transportes (exceto veículos)'),
(289, 517, 559, 'Outros Bens Duráveis', 'Bens duráveis diversos, incluindo artigos esportivos e de recreação, brinquedos e hobbys, refugo e sucatas, joalheria, relojoarias, pedras e metais preciosos, etc.'),
(291, 517, 560, 'Papelaria', 'Papel para escrever e imprimir, artigos de papelaria para escritório, produtos de papel para uso pessoal e industrial'),
(292, 517, 560, 'Farmácias e Drogarias', 'Drogas medicinais, perfumes e demais produtos farmacêuticos'),
(293, 517, 560, 'Roupas e Acessórios', 'Vestuário (roupas e acessórios para homens, rapazes, senhoras, crianças e bebês), calçados, artigos de armarinnho, tecidos por metro e aviamentos'),
(294, 517, 560, 'Produtos Alimentícios', 'Alimentos em geral: embalados, congelados, laticínios, aves, ovos, artigos de confeitaria, peixes e frutos do mar, carnes e derivados, frutas e legumes, etc.'),
(295, 517, 560, 'Matéria Prima Agropecuária', 'Matérias primas de origem animal e vegetal, como cereais, gado, etc.'),
(296, 517, 560, 'Produtos Químicos', 'Produtos químicos, plásticos e relacionados'),
(297, 517, 560, 'Petróleo e Derivados', 'Petróleo e produtos derivados de petróleo, incluindo postos e terminais de petróleo e derivados a granel'),
(298, 517, 560, 'Bebidas Alcoólicas', 'Cervejas, vinhos e bebidas alcoólicas destiladas e fermentadas'),
(299, 517, 560, 'Outros Bens Não Duráveis', 'Demais bens não duráveis, incluindo produtos para uso agropecuário, livros, revistas e jornais, flores, fumo, tintas, vernizes, etc.'),
(301, 517, 561, 'Madeira e Material de Construção', 'Madeiras e materiais de construção'),
(302, 517, 561, 'Tintas e Vidros', 'Lojas de tintas, vidros e papel de parede'),
(303, 517, 561, 'Ferragens', 'Lojas de ferragens'),
(304, 517, 561, 'Floricultura e Jardinagem', 'Floriculturas e lojas de artigos para jardinagem'),
(305, 517, 561, 'Revenda de Trailers', 'Revendedores de residências móveis (trailers, motor-home e assemelhados)'),
(307, 517, 562, 'Lojas de Departamento', 'Lojas de departamentos'),
(308, 517, 562, 'Bazares e Armarinhos', 'Bazares e mercearias'),
(309, 517, 562, 'Shopping Centers', 'Shopping Centers'),
(310, 517, 562, 'Outras Lojas', 'Demais lojas de mercadorias em geral'),
(312, 517, 563, 'Supermercados e Quitandas', 'Supermercados e quitandas: comércio de alimentos em geral'),
(313, 517, 563, 'Açougues e Peixarias', 'Comércio de carnes e peixes'),
(314, 517, 563, 'Frutas e Vegetais', 'Comércio de frutas e vegetais'),
(315, 517, 563, 'Doces e Confeitarias', 'Comércio de Doces Confeitarias'),
(316, 517, 563, 'Laticínios', 'Laticínios'),
(317, 517, 563, 'Padarias', 'Padarias'),
(318, 517, 563, 'Outros Alimentos', 'Outros alimentos'),
(320, 517, 564, 'Carros Novos e Usados', 'Agências e concessiónárias de automóveis: venda de carros novos e usados'),
(321, 517, 564, 'Carros Usados', 'Agências de compra e venda de automóveis usados'),
(322, 517, 564, 'Autopeças', 'Lojas de peças e acessórios para automóveis'),
(323, 517, 564, 'Postos de Serviços', 'Postos de Serviços: comércio de combustíveis para automóveis e afins'),
(324, 517, 564, 'Barcos', 'Compra e venda de barcos'),
(325, 517, 564, 'Veículos recreativos', 'Compra e venda de veículos recreativos (p.ex. buggys)'),
(326, 517, 564, 'Motocicletas', 'Compra e venda de motocicletas'),
(327, 517, 564, 'Demais automotivos', 'Demais comércios relacionados a produtos automotivos'),
(329, 517, 565, 'Roupas Masculinas', 'Lojas de roupas masculinas'),
(330, 517, 565, 'Roupas Femininas', 'Lojas de roupas femininas'),
(331, 517, 565, 'Acessórios Femininos', 'Lojas de acessórios femininos'),
(332, 517, 565, 'Roupa Infantil', 'Lojas de roupas infantis'),
(333, 517, 565, 'Roupas em Geral', 'Lojas de roupas que comercializam roupas masculinas, femininas e infantis'),
(334, 517, 565, 'Calçados', 'Lojas de calçados'),
(335, 517, 565, 'Confecções e Acessórios', 'Lojas de confecções e acessórios em geral'),
(337, 517, 566, 'Móveis Domésticos', 'Lojas de móveis domésticos, pisos, cortinas, estofados e acessórios'),
(338, 517, 566, 'Eletrodomésticos', 'Lojas de eletrodomésticos'),
(339, 517, 566, 'Aúdio, Vídeo e Computadores', 'Lojas de rádio, televisão, artigos eletrônicos, computadores, periféricos, discos e fitas e instrumentos musicais'),
(341, 517, 567, 'Bares e Restaurantes', 'Restaurantes, bares e casas noturnas'),
(343, 517, 568, 'Farmácias e Drogarias', 'Farmácias e drogarias'),
(344, 517, 568, 'Adegas', 'Adegas; lojas especializadas em bebidas alcoólicas'),
(345, 517, 568, 'Artigos Usados', 'Lojas de artigos usados'),
(346, 517, 568, 'Outros Produtos', 'Lojas de artigos esportivos, bicicletas, livrarias, papelarias, joalherias, brinquedos e jogos, câmeras e material fotográfico, souvenirs, presentes e novidades, malas e bolsas de couro, artigos para costura'),
(347, 517, 568, 'Varejo sem Loja', 'Varejistas sem lojas abertas ao público: venda por mala direta, venda por máquinas automáticas, vendas por telemarketing, etc.'),
(348, 517, 568, 'Revenda de Combustível', 'Revendedores de combustíveis (derivados de petróleo, álcool carburante e gás natural e liqüefeito)'),
(349, 517, 568, 'Outros Varejistas', 'Comércio varejista não classificado acima, incluindo floriculturas, tabacarias, bancas de revistas e jornais, óticas, etc.'),
(351, 518, 569, 'Banco Central', 'Banco Central e órgãos públicos relacionados à atividade financeira'),
(352, 518, 569, 'Bancos Comerciais Nacionais', 'Bancos comerciais nacionais, de capital estatal, público ou privado'),
(353, 518, 569, 'Instituições de Poupança', 'Instituições de poupança'),
(354, 518, 569, 'Cooperativas de Crédito', 'Cooperativas de crédito'),
(355, 518, 569, 'Bancos Estrangeiros', 'Atividades bancárias estrangeiras, filiais e agências de bancos estrangeiros'),
(356, 518, 569, 'Outros Serviços Bancários', 'Demais funções e serviços relativos a bancos de depósito'),
(358, 518, 570, 'Crédito Oficial', 'Agências e órgãos de crédito pertencentes ao governo'),
(359, 518, 570, 'Administradoras de Cartão de Crédito', 'Instituições que emitem e administram cartões de crédito'),
(360, 518, 570, 'Administradoras de Tickets e Vales', 'Instituições que emitem e administram tickets e vales para refeição, combustível, etc.'),
(361, 518, 570, 'Crédito ao Consumidor', 'Instituições de crédito ao consumidor'),
(362, 518, 570, 'Crédito Mercantil/Leasing', 'Instituições de crédito mercantil e leasing para empresas'),
(363, 518, 570, 'Crédito Hipotecário', 'Bancos, corretoras e companhias de crédito hipotecário'),
(365, 518, 571, 'Corretoras de Ações e Títulos Públicos', 'Companhias, agentes e representantes de ações e títulos públicos'),
(366, 518, 571, 'Corretoras de Commodities', 'Agentes e negociantes de contratos de commodities'),
(367, 518, 571, 'Bolsas de Valores', 'Bolsas de valores e demais instituições de negociação de ações e commodities'),
(368, 518, 571, 'Outros Serviços com Ações', 'Serviços relacionados à Bolsa de Valores ou de commodities, p.ex. recomendações de investimento'),
(370, 518, 572, 'Seguro de Vida', 'Seguro de vida'),
(371, 518, 572, 'Seguro de Saúde', 'Planos de seguro de acidente e de assistência médica'),
(372, 518, 572, 'Seguro de Sinistros', 'Seguro de incêndio, marítimo e acidentes'),
(373, 518, 572, 'Seguro de Ações', 'Seguro de ações'),
(374, 518, 572, 'Seguro de Títulos', 'Seguro de títulos'),
(375, 518, 572, 'Fundos de Pensão', 'Fundos de pensão, saúde, previdência privada'),
(376, 518, 572, 'Outros Tipos de Seguro', 'Demais seguradoras, não classificadas'),
(378, 518, 573, 'Corretoras de Seguros', 'Agentes, despachantes e Serviços de seguros'),
(380, 518, 574, 'Administração Imobiliária', 'Administradoras de propriedade imobiliária (prédios residenciais e não residenciais, operadores de campings) e arrendadores (incluindo leasing)'),
(381, 518, 574, 'Corretores Imobiliários', 'Agentes de comercialização de propriedades imobiliárias'),
(382, 518, 574, 'Cartórios', 'Escritórios de registro de títulos'),
(383, 518, 574, 'Loteadores e Incorporadores', 'Loteadores e incorporadores, inclusive de cemitérios'),
(385, 518, 575, 'Holdings', 'Empresas de holding, inclusive de bancos'),
(386, 518, 575, 'Bancos de Investimentos', 'Bancos e escritórios de gerenciamento de investimentos'),
(387, 518, 575, 'Administradoras de Fundos', 'Administração de fundos, inclusive de caridade, religiosos e educacionais'),
(388, 518, 575, 'Outros Investimentos', 'Investimentos diversos'),
(390, 522, 576, 'Hotéis e Motéis', 'Hotéis e motéis'),
(391, 522, 576, 'Pensões e Pensionatos', 'Pensões e pensionatos'),
(392, 522, 576, 'Campings', 'Acampamentos e parque para veículos recreativos'),
(393, 522, 576, 'Hotéis de Associações', 'Hotéis pertencentes a associações, de uso restrito aos associados'),
(395, 522, 577, 'Lavanderia e Limpeza de Ropas', 'Serviços de lavanderia (familiares e comerciais, com e sem passagem; lavanderias automáticas, a seco; lvanderias industriais), limpeza de carpetes e estofados, e conservação de roupas'),
(396, 522, 577, 'Estudios de Foto & Vídeo', 'Estudios fotográficos e gravação de vídeos'),
(397, 522, 577, 'Salões de Beleza', 'Salões de beleza'),
(398, 522, 577, 'Barbearias', 'Barbearias'),
(399, 522, 577, 'Sapatarias', 'Sapatarias'),
(400, 522, 577, 'Funerárias e Crematórios', 'Serviços funerários e crematórios'),
(401, 522, 577, 'Outros Serviços Pessoais', 'Outros Serviços pessoais, p.ex. preparação de declarações de impostos'),
(403, 522, 578, 'Publicidade', 'Agências de propaganda, serviços de outdoor, agentes de propaganda para rádio, televisão e publicações, etc.'),
(404, 522, 578, 'Proteção ao Crédito e Cobrança', 'Serviços de cobrança e serviços de informações de crédito'),
(405, 522, 578, 'Mala Direta e Fotocópias', 'Serviços de propaganda por mala direta, fotocópias e duplicações, arte, desenho e fotografia para fins comerciais'),
(406, 522, 578, 'Serviços em Edificações', 'Serviços para residências e edifícios comerciais: dedetização, controle de pragas, limpeza e manutenção, etc.'),
(407, 522, 578, 'Aluguel de Equipamentos', 'Aluguel e leasing de equipamentos médicos, para construção pesada, etc.'),
(408, 522, 578, 'Mão de Obra', 'Serviços de oferta de profissionais: agências de empregos e de mão de obra temporária'),
(409, 522, 578, 'Promoção de Eventos Comerciais', 'Serviços de promoção e organização de feiras e eventos com objetivo comercial'),
(410, 522, 578, 'Outros Serviços Comerciais', 'Demais serviços comerciais, incluindo transporte de valores, segurança, detetives e agências de notícias'),
(412, 522, 579, 'Aluguel de Carros sem Motorista', 'Aluguel e leasing de veículos de passeio e de caminhões sem motorista'),
(413, 522, 579, 'Estacionamentos', 'Estacionamento de automóveis'),
(414, 522, 579, 'Oficinas de Automóveis', 'Oficina de conserto de automóveis: pintura, escapamento, pneus, recauchutagem, vidros, câmbio, em geral, etc.'),
(415, 522, 579, 'Outros Serviços Automotivos', 'Demais serviços em veículos (exceto conserto), incluindo lavagem manual e automática de veículos'),
(417, 522, 580, 'Oficinas de Consertos Elétricos', 'Oficinas de conserto de produtos elétricos e eletrônicos (rádio, televisão, refrigeração, ar condicionado e outros)'),
(418, 522, 580, 'Conserto de Relógios e Jóias', 'Consertos de relógios e jóias'),
(419, 522, 580, 'Conserto de Móveis e Estofados', 'Conserto de móveis e estofados'),
(420, 522, 580, 'Outros Consertos', 'Demais oficinas de consertos e serviços relacionados, incluindo conserto de soldas, serviços de rebobinagem, etc.'),
(422, 522, 581, 'Produção de Filmes', 'Produções de filmes cinematográficos e vídeos e serviços relacionados'),
(423, 522, 581, 'Distribuição de Filmes', 'Distribuição de filmes cinematográficos e vídeos e serviços relacionados'),
(424, 522, 581, 'Cinemas', 'Cinemas e drive-ins'),
(425, 522, 581, 'Locadoras de Fitas de Vídeo', 'Aluguel de fitas de vídeo'),
(427, 522, 582, 'Danças', 'Estúdios, escolas e salões de dança'),
(428, 522, 582, 'Produtores Teatrais/Grupos Music', 'Produtores e serviços teatrais; solitas, bandas, conjuntos e orquestras musicais'),
(429, 522, 582, 'Boliches', 'Boliches'),
(430, 522, 582, 'Esportes Profissionais', 'Esportes profissionais, incluindo clubes, promotores, corridas de automóveis, autódromos, etc.'),
(431, 522, 582, 'Outros Serviços Recreativos', 'Serviços diversos de diversão e recreação, incluindo academias de ginástica, pistas públicas para práticas de esporte, diversões operadas com fichas e/ou moedas, parques de diversões, clubes recreativos e esportivos e outros entretenimentos'),
(433, 522, 583, 'Consultórios/Clínicas Médicas', 'Consultórios e clínicas médicas'),
(434, 522, 583, 'Consultórios/Clínicas Dentárias', 'Consultórios e clínicas dentárias'),
(435, 522, 583, 'Consultórios/Clínicas Especiliz.', 'Consultórios e clínicas de profissionais de saúde especializados, p.ex. osteopatia, optiometria, pediatras, etc.'),
(436, 522, 583, 'Enfermagem e Casas de Repouso', 'Instalações de enfermagem, recuperação, sanatórios e casas de repouso'),
(437, 522, 583, 'Hospitais', 'Hospitais de medicina geral e especializados (p.ex. psiquiatría, cardiología, oncología, etc)'),
(438, 522, 583, 'Laboratórios', 'Laboratórios médicos e odontológicos'),
(439, 522, 583, 'Saúde a Domicílo', 'Serviços médicos executados na residência do paciente'),
(440, 522, 583, 'Outros Serviços de Saúde', 'Demais serviços de saúde e afins, incluindo diálise renal, ambulatórios especializados, etc.'),
(442, 522, 584, 'Serviços de Advocacia', 'Serviços de Advocacia'),
(444, 522, 585, 'Escolas', 'Escolas Primárias e Secundárias'),
(445, 522, 585, 'Universidades', 'Serviços educacionais superiores: universidades, faculdades e institutos tecnológicos'),
(446, 522, 585, 'Bibliotecas', 'Bibliotecas'),
(447, 522, 585, 'Escolas Técnicas', 'Escolas técnicas em agronomia, comércio, secretariado, processamento de dados, eletrônica, etc.'),
(448, 522, 585, 'Pré-escolas', 'Escolas Infantis em nível préprimário'),
(449, 522, 585, 'Outros Serviços Educacionais', 'Demais serviços de educação, incluindo conservatórios, escolas de línguas, etc.'),
(451, 522, 586, 'Serviços Sociais', 'Serviços sociais individuais e familiares'),
(452, 522, 586, 'Treinamento Profissional', 'Serviços de treinamento para o trabalho e reabilitação vocacional'),
(453, 522, 586, 'Creches', 'Creches'),
(454, 522, 586, 'Assistência Residencial', 'Assistência residencial'),
(455, 522, 586, 'Outros Serviços Sociais', 'Demais serviços sociais'),
(457, 522, 587, 'Museus e Galerias de Arte', 'Museus e galerias de arte'),
(458, 522, 587, 'Jardins Zoológicos e Botânicos', 'Jardins zoológicos, botânicos, aquários'),
(460, 522, 588, 'Associações Empresariais', 'Associações de empresas'),
(461, 522, 588, 'Associações Profissionais', 'Organizações profissionais'),
(462, 522, 588, 'Sindicatos', 'Sindicatos'),
(463, 522, 588, 'Associações Cívicas e Sociais', 'Associações cívicas e sociais'),
(464, 522, 588, 'Associações Políticas', 'Organizações políticas, inclusive partidos'),
(465, 522, 588, 'Associações Religiosas', 'Organizações religiosas'),
(466, 522, 588, 'Clubes de Lazer', 'Clubes destinados a lazer e recreação, com prática eventual e não profissional de esportes'),
(467, 522, 588, 'Outras Associações', 'Organizações, S/C'),
(468, 522, 588, 'Condomínios', 'Condomínios'),
(470, 522, 589, 'Engenharia/Arquitetura/Agrimensura', 'Serviços de engenharia, arquitetura e agrimensura'),
(471, 522, 589, 'Contabilidade e Auditoria', 'Serviços de contabilidade, auditoria e escrituração'),
(472, 522, 589, 'Pesquisa e Desenvolvimento', 'Serviços de pesquisa, desenvolvimentos e testes, comerciais e não comerciais, físicos, biológicos, econômicos, educacionais, etc.'),
(473, 522, 589, 'Gerenciamento e Relações Pública', 'Serviços gerenciais, consultoria gerencial, relações públicas, gerenciamento de instalações e demais consultorias comerciais'),
(475, 522, 590, 'Serviços Domésticos', 'Serviços domésticos privados'),
(477, 522, 591, 'Outros Serviços', 'Demais Serviços'),
(479, 524, 592, 'Poder Executivo', 'Poder executivo: presidência, ministérios, governos estaduais, municipais e secretarias'),
(480, 524, 592, 'Poder Legislativo', 'Órgãos legislativos: congresso, assembléias estaduais e municipais'),
(481, 524, 592, 'Outros Órgãos Governamentais', 'Governo geral S/C'),
(483, 524, 593, 'Poder Judicial', 'Tribunais'),
(484, 524, 593, 'Ordem Pública', 'Ordem pública e segurança: polícia, promotorias, presídios, bombeiros, etc.'),
(486, 524, 594, 'Tributação', 'Finanças, tributação e política monetária'),
(490, 524, 597, 'Embaixadas e Consulados', 'Embaixadas e Consulados e demais órgãos da diplomacia internacional'),
(491, 524, 597, 'Organismos Internacionais', 'Organismos internacionais (ONU, etc.)'),
(493, 524, 598, 'Forças Armadas', 'Forças Armadas: Exército, Marinha e Aeronaútica'),
(494, 524, 598, 'Órgãos de Inteligência', 'Órgãos de Inteligência Pública'),
(496, 524, 599, 'Fundações', 'Fundações filantrópicas, corporativas, familiares, comunitárias e especiais'),
(498, 520, 600, 'Indústria de Informática', 'Indústria de computadores, terminais, monitores, diskettes, fitas, periféricos'),
(500, 520, 601, 'Distribuidores de Informática', 'Distribuidores de produtos de informática (atacado)'),
(501, 520, 601, 'Revendas de Informática', 'Revendas de produtos de informática (varejo)'),
(503, 520, 602, 'Aluguel e Leasing', 'Aluguel e Leasing de Computadores'),
(504, 520, 602, 'Birôs e CPDs terceirizados', 'Birôs e terceirização de centros de processamento de dados'),
(505, 520, 602, 'Conserto de Computadores', 'Serviços de manutenção e reparo de computadores, periféricos e equipamentos relacionados'),
(506, 520, 602, 'Treinamento em Informática', 'Treinamento em Informática'),
(507, 520, 602, 'Serviços de Consultoria', 'Serviços de consultoria em informática'),
(508, 520, 602, 'Software sob Encomenda', 'Desenvolvimento de software sob contrato'),
(509, 520, 602, 'Software House', 'Software House: desenvolvimento de software para comercialização posterior'),
(510, 520, 602, 'Provedor de Acesso Internet', 'Provedor de Acesso à Internet'),
(511, 520, 602, 'Serviços para Internet', 'Serviços relacionados à Internet, exceto provedor de acesso'),
(512, 520, 602, 'Serviços de Informática', 'Demais serviços relacionados a computadores, ou vários dos anteriores'),
(513, 520, 602, 'Subsidiárias de empresas estrangeiras de software', 'Escritórios de representação, promoção e suporte de empresas estrangeiras'),
(514, 520, 602, 'Integradores de Redes', 'Integradores de redes de computadores e serviços relacionados'),
(515, 520, 602, 'Serviços de Informação', 'Serviços para a obtenção de informações'),
(516, 520, 602, 'Internet Data Center', 'Internet Data Center');
